# .NET Desktop

# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.300'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'nwjsCompilerCLI\nwjsCompilerCLI.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'nwjsCompilerCLI\nwjsCompilerCLI.csproj'
    arguments: '--self-contained true -c Release -r win-x64'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'nwjsCompilerCLI\bin\Release\netcoreapp3.1\win-x64\publish'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\CLI'
    OverWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\CLI'
    ArtifactName: 'clidrop'
    publishLocation: 'Container'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'nwjsCookToolUI\nwjsCookToolUI.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'nwjsCoookToolUI\nwjsCookToolUI.csproj'
    arguments: '--self-contained true -c Release -r win-x64'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'nwjsCookToolUI\bin\Release\netcoreapp3.1\win-x64\publish'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\UI'
    OverWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\CLI'
    ArtifactName: 'uidrop'
    publishLocation: 'Container'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'