//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMMVCookTool.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RMMVCookTool.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string BrowseUiText {
            get {
                return ResourceManager.GetString("BrowseUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromium Flags.
        /// </summary>
        internal static string ChromiumFlagsUiText {
            get {
                return ResourceManager.GetString("ChromiumFlagsUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string DoneText {
            get {
                return ResourceManager.GetString("DoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable NodeJS?.
        /// </summary>
        internal static string EnableNodeJSCheckBoxText {
            get {
                return ResourceManager.GetString("EnableNodeJSCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essentials.
        /// </summary>
        internal static string EssentialsGroupString {
            get {
                return ResourceManager.GetString("EssentialsGroupString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the folder. Please check that you have permission to read and write on the folder..
        /// </summary>
        internal static string FileAccessError {
            get {
                return ResourceManager.GetString("FileAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You picked a file that is outside of the project&apos;s file. Please pick a file within the project..
        /// </summary>
        internal static string FileOutsideOfProjectError {
            get {
                return ResourceManager.GetString("FileOutsideOfProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File Stream went kaput..
        /// </summary>
        internal static string FileStreamErrorText {
            get {
                return ResourceManager.GetString("FileStreamErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ID.
        /// </summary>
        internal static string GameIDUiString {
            get {
                return ResourceManager.GetString("GameIDUiString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Info.
        /// </summary>
        internal static string GameInfoTabText {
            get {
                return ResourceManager.GetString("GameInfoTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Name.
        /// </summary>
        internal static string GameNameUiText {
            get {
                return ResourceManager.GetString("GameNameUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Package Metadata Editor.
        /// </summary>
        internal static string GamePackageMetadataEditorTitleText {
            get {
                return ResourceManager.GetString("GamePackageMetadataEditorTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string GameVersionUiString {
            get {
                return ResourceManager.GetString("GameVersionUiString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string HeightUiText {
            get {
                return ResourceManager.GetString("HeightUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML file location.
        /// </summary>
        internal static string HTMLFileLocationUiString {
            get {
                return ResourceManager.GetString("HTMLFileLocationUiString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML File|*.html.
        /// </summary>
        internal static string HTMLFileText {
            get {
                return ResourceManager.GetString("HTMLFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Location.
        /// </summary>
        internal static string IconLocationUiText {
            get {
                return ResourceManager.GetString("IconLocationUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Full Screen.
        /// </summary>
        internal static string InFullScreenListItemText {
            get {
                return ResourceManager.GetString("InFullScreenListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Kiosk Mode.
        /// </summary>
        internal static string InKioskModeListItemText {
            get {
                return ResourceManager.GetString("InKioskModeListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IO Exception occurred. Is an app using the package.json file?.
        /// </summary>
        internal static string IOErrorText {
            get {
                return ResourceManager.GetString("IOErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript Flags.
        /// </summary>
        internal static string JavaScriptFlagsUiText {
            get {
                return ResourceManager.GetString("JavaScriptFlagsUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Height.
        /// </summary>
        internal static string MinimumHeightUiText {
            get {
                return ResourceManager.GetString("MinimumHeightUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Width.
        /// </summary>
        internal static string MinimumWidthUiText {
            get {
                return ResourceManager.GetString("MinimumWidthUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Cursor.
        /// </summary>
        internal static string MouseCursorListItemText {
            get {
                return ResourceManager.GetString("MouseCursorListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NoneListItemText {
            get {
                return ResourceManager.GetString("NoneListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.js features.
        /// </summary>
        internal static string NWJsFeaturesGroupText {
            get {
                return ResourceManager.GetString("NWJsFeaturesGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG File|*.png.
        /// </summary>
        internal static string PNGFileText {
            get {
                return ResourceManager.GetString("PNGFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the project is too long. Please shorten the path..
        /// </summary>
        internal static string ProjectPathTooLongErrorText {
            get {
                return ResourceManager.GetString("ProjectPathTooLongErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the location of the project..
        /// </summary>
        internal static string ProjectPickerText {
            get {
                return ResourceManager.GetString("ProjectPickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizable Window?.
        /// </summary>
        internal static string ResizableWindowUiText {
            get {
                return ResourceManager.GetString("ResizableWindowUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string ResolutionUiText {
            get {
                return ResourceManager.GetString("ResolutionUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package metadata file was saved successfully..
        /// </summary>
        internal static string SaveCompleteText {
            get {
                return ResourceManager.GetString("SaveCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Center.
        /// </summary>
        internal static string ScreenCenterListItemText {
            get {
                return ResourceManager.GetString("ScreenCenterListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsUiText {
            get {
                return ResourceManager.GetString("SettingsUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        internal static string StartUiText {
            get {
                return ResourceManager.GetString("StartUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string WidthUiText {
            get {
                return ResourceManager.GetString("WidthUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed.
        /// </summary>
        internal static string WindowedListItemText {
            get {
                return ResourceManager.GetString("WindowedListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string WindowGroupText {
            get {
                return ResourceManager.GetString("WindowGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Position.
        /// </summary>
        internal static string WindowPositionUiText {
            get {
                return ResourceManager.GetString("WindowPositionUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Settings.
        /// </summary>
        internal static string WindowSettingsUiText {
            get {
                return ResourceManager.GetString("WindowSettingsUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Size.
        /// </summary>
        internal static string WindowSizeGroupText {
            get {
                return ResourceManager.GetString("WindowSizeGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Title.
        /// </summary>
        internal static string WindowTitleUiText {
            get {
                return ResourceManager.GetString("WindowTitleUiText", resourceCulture);
            }
        }
    }
}
