//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMMVCookTool.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RMMVCookTool.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string BrowseUiText {
            get {
                return ResourceManager.GetString("BrowseUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromium Flags.
        /// </summary>
        public static string ChromiumFlagsUiText {
            get {
                return ResourceManager.GetString("ChromiumFlagsUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string CompleteText {
            get {
                return ResourceManager.GetString("CompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings will be used for new projects added from this point on..
        /// </summary>
        public static string DefaultSettingsUpdatedMessage {
            get {
                return ResourceManager.GetString("DefaultSettingsUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your default settings have been updated..
        /// </summary>
        public static string DefaultSettingsUpdatedText {
            get {
                return ResourceManager.GetString("DefaultSettingsUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string DoneText {
            get {
                return ResourceManager.GetString("DoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable NodeJS?.
        /// </summary>
        public static string EnableNodeJSCheckBoxText {
            get {
                return ResourceManager.GetString("EnableNodeJSCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking on the &quot;More Details&quot; button will show the stack trace. Make sure to include this if you are filling a bug report, since it can help with diagnosing the bug..
        /// </summary>
        public static string ErrorDetailsMessage {
            get {
                return ResourceManager.GetString("ErrorDetailsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ack! An error has occured..
        /// </summary>
        public static string ErrorOccuredTitle {
            get {
                return ResourceManager.GetString("ErrorOccuredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essentials.
        /// </summary>
        public static string EssentialsGroupString {
            get {
                return ResourceManager.GetString("EssentialsGroupString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the folder. Please check that you have permission to read and write on the folder..
        /// </summary>
        public static string FileAccessError {
            get {
                return ResourceManager.GetString("FileAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You picked a file that is outside of the project&apos;s file. Please pick a file within the project..
        /// </summary>
        public static string FileOutsideOfProjectError {
            get {
                return ResourceManager.GetString("FileOutsideOfProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File Stream went kaput..
        /// </summary>
        public static string FileStreamErrorText {
            get {
                return ResourceManager.GetString("FileStreamErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ID.
        /// </summary>
        public static string GameIDUiString {
            get {
                return ResourceManager.GetString("GameIDUiString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Info.
        /// </summary>
        public static string GameInfoTabText {
            get {
                return ResourceManager.GetString("GameInfoTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Name.
        /// </summary>
        public static string GameNameUiText {
            get {
                return ResourceManager.GetString("GameNameUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Package Metadata Editor.
        /// </summary>
        public static string GamePackageMetadataEditorTitleText {
            get {
                return ResourceManager.GetString("GamePackageMetadataEditorTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string GameVersionUiString {
            get {
                return ResourceManager.GetString("GameVersionUiString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string HeightUiText {
            get {
                return ResourceManager.GetString("HeightUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML file location.
        /// </summary>
        public static string HTMLFileLocationUiString {
            get {
                return ResourceManager.GetString("HTMLFileLocationUiString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML File|*.html.
        /// </summary>
        public static string HTMLFileText {
            get {
                return ResourceManager.GetString("HTMLFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Location.
        /// </summary>
        public static string IconLocationUiText {
            get {
                return ResourceManager.GetString("IconLocationUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Full Screen.
        /// </summary>
        public static string InFullScreenListItemText {
            get {
                return ResourceManager.GetString("InFullScreenListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Kiosk Mode.
        /// </summary>
        public static string InKioskModeListItemText {
            get {
                return ResourceManager.GetString("InKioskModeListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IO Exception occurred. Is an app using the package.json file?.
        /// </summary>
        public static string IOErrorText {
            get {
                return ResourceManager.GetString("IOErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript Flags.
        /// </summary>
        public static string JavaScriptFlagsUiText {
            get {
                return ResourceManager.GetString("JavaScriptFlagsUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\deff3\adeflang1025
        ///{\fonttbl{\f0\froman\fprq2\fcharset0 Times New Roman;}{\f1\froman\fprq2\fcharset2 Symbol;}{\f2\fswiss\fprq2\fcharset0 Arial;}{\f3\froman\fprq2\fcharset161 Liberation Serif{\*\falt Times New Roman};}{\f4\froman\fprq2\fcharset161 Liberation Sans{\*\falt Arial};}{\f5\froman\fprq2\fcharset161 Liberation Mono{\*\falt Courier New};}{\f6\fmodern\fprq1\fcharset128 Lucida Console;}{\f7\fswiss\fprq2\fcharset128 Segoe UI;}{\f8\fnil\fprq2\fcharset161 Arial;}{\f9\fnil\fprq2\fcharset161 Li [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Height.
        /// </summary>
        public static string MinimumHeightUiText {
            get {
                return ResourceManager.GetString("MinimumHeightUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Width.
        /// </summary>
        public static string MinimumWidthUiText {
            get {
                return ResourceManager.GetString("MinimumWidthUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Cursor.
        /// </summary>
        public static string MouseCursorListItemText {
            get {
                return ResourceManager.GetString("MouseCursorListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NoneListItemText {
            get {
                return ResourceManager.GetString("NoneListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.js features.
        /// </summary>
        public static string NWJsFeaturesGroupText {
            get {
                return ResourceManager.GetString("NWJsFeaturesGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG File|*.png.
        /// </summary>
        public static string PNGFileText {
            get {
                return ResourceManager.GetString("PNGFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a project from the list. You may have to add it to the list (if you haven&apos;t done so)..
        /// </summary>
        public static string ProjectMessageNotSelected_Details {
            get {
                return ResourceManager.GetString("ProjectMessageNotSelected_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project was not selected..
        /// </summary>
        public static string ProjectNotSelectedMessage {
            get {
                return ResourceManager.GetString("ProjectNotSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the project is too long. Please shorten the path..
        /// </summary>
        public static string ProjectPathTooLongErrorText {
            get {
                return ResourceManager.GetString("ProjectPathTooLongErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the location of the project..
        /// </summary>
        public static string ProjectPickerText {
            get {
                return ResourceManager.GetString("ProjectPickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizable Window?.
        /// </summary>
        public static string ResizableWindowUiText {
            get {
                return ResourceManager.GetString("ResizableWindowUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string ResolutionUiText {
            get {
                return ResourceManager.GetString("ResolutionUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package metadata file was saved successfully..
        /// </summary>
        public static string SaveCompleteText {
            get {
                return ResourceManager.GetString("SaveCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Center.
        /// </summary>
        public static string ScreenCenterListItemText {
            get {
                return ResourceManager.GetString("ScreenCenterListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the location of the SDK folder..
        /// </summary>
        public static string SDKPickerText {
            get {
                return ResourceManager.GetString("SDKPickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsUiText {
            get {
                return ResourceManager.GetString("SettingsUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project&apos;s settings have been updated..
        /// </summary>
        public static string SProjectSettingsUpdatedText {
            get {
                return ResourceManager.GetString("SProjectSettingsUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- The Stack Trace is below this line ---.
        /// </summary>
        public static string StackTraceLine {
            get {
                return ResourceManager.GetString("StackTraceLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        public static string StartUiText {
            get {
                return ResourceManager.GetString("StartUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string WidthUiText {
            get {
                return ResourceManager.GetString("WidthUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed.
        /// </summary>
        public static string WindowedListItemText {
            get {
                return ResourceManager.GetString("WindowedListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string WindowGroupText {
            get {
                return ResourceManager.GetString("WindowGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Position.
        /// </summary>
        public static string WindowPositionUiText {
            get {
                return ResourceManager.GetString("WindowPositionUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Settings.
        /// </summary>
        public static string WindowSettingsUiText {
            get {
                return ResourceManager.GetString("WindowSettingsUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Size.
        /// </summary>
        public static string WindowSizeGroupText {
            get {
                return ResourceManager.GetString("WindowSizeGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Title.
        /// </summary>
        public static string WindowTitleUiText {
            get {
                return ResourceManager.GetString("WindowTitleUiText", resourceCulture);
            }
        }
    }
}
