//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nwjsCookToolUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nwjsCookToolUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutUiText {
            get {
                return ResourceManager.GetString("AboutUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddUiText {
            get {
                return ResourceManager.GetString("AddUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Compile.
        /// </summary>
        public static string BatchCompileUiText {
            get {
                return ResourceManager.GetString("BatchCompileUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing binary files (if present)....
        /// </summary>
        public static string BinRemovalProgressText {
            get {
                return ResourceManager.GetString("BinRemovalProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing binary files from .
        /// </summary>
        public static string BinRemovalStatusText {
            get {
                return ResourceManager.GetString("BinRemovalStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Removing binary files from the project (if there are)...
        ///.
        /// </summary>
        public static string BinRemovalText {
            get {
                return ResourceManager.GetString("BinRemovalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string BrowseUiText {
            get {
                return ResourceManager.GetString("BrowseUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation complete!.
        /// </summary>
        public static string CompilationCompleteText {
            get {
                return ResourceManager.GetString("CompilationCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Compiled on .
        /// </summary>
        public static string CompiledOutputText {
            get {
                return ResourceManager.GetString("CompiledOutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling scripts in the js folder....
        /// </summary>
        public static string CompileJsFolderProgressText {
            get {
                return ResourceManager.GetString("CompileJsFolderProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nwjs Compiler is missing..
        /// </summary>
        public static string CompilerMissingText {
            get {
                return ResourceManager.GetString("CompilerMissingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler Status.
        /// </summary>
        public static string CompilerStatusUiText {
            get {
                return ResourceManager.GetString("CompilerStatusUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling .
        /// </summary>
        public static string CompileText {
            get {
                return ResourceManager.GetString("CompileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling scripts in the .
        /// </summary>
        public static string CompileText1 {
            get {
                return ResourceManager.GetString("CompileText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile.
        /// </summary>
        public static string CompileUiText {
            get {
                return ResourceManager.GetString("CompileUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Compiling .
        /// </summary>
        public static string CompilingText {
            get {
                return ResourceManager.GetString("CompilingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by AceOfAces. Licensed under GNU General Public License v3..
        /// </summary>
        public static string DevInfoUiText {
            get {
                return ResourceManager.GetString("DevInfoUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string DoneText {
            get {
                return ResourceManager.GetString("DoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ack! An error occured! See the output in the About tab..
        /// </summary>
        public static string ErrorOccuredText {
            get {
                return ResourceManager.GetString("ErrorOccuredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed!.
        /// </summary>
        public static string FailedText {
            get {
                return ResourceManager.GetString("FailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// Copying files to a temporary area...
        ///.
        /// </summary>
        public static string FileCopyText {
            get {
                return ResourceManager.GetString("FileCopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension for compiled files:.
        /// </summary>
        public static string FileExtensionUiText {
            get {
                return ResourceManager.GetString("FileExtensionUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  folder....
        /// </summary>
        public static string FolderText {
            get {
                return ResourceManager.GetString("FolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add the folders you want the JavaScript files to be compiled..
        /// </summary>
        public static string NoJSFilesPresent {
            get {
                return ResourceManager.GetString("NoJSFilesPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t operate on an non-existent folder..
        /// </summary>
        public static string NonExistantFolderText {
            get {
                return ResourceManager.GetString("NonExistantFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string OutputUiText {
            get {
                return ResourceManager.GetString("OutputUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// Creating package...
        ///.
        /// </summary>
        public static string PackageCreationText {
            get {
                return ResourceManager.GetString("PackageCreationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package the game into package.nw.
        /// </summary>
        public static string PackageProgramUiText {
            get {
                return ResourceManager.GetString("PackageProgramUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging....
        /// </summary>
        public static string PackaginStatusText {
            get {
                return ResourceManager.GetString("PackaginStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Information.
        /// </summary>
        public static string ProgramInfoUiText {
            get {
                return ResourceManager.GetString("ProgramInfoUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPG Maker MV Cook Tool.
        /// </summary>
        public static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Folders.
        /// </summary>
        public static string ProjectFoldersUiText {
            get {
                return ResourceManager.GetString("ProjectFoldersUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Location.
        /// </summary>
        public static string ProjectLocationUiText {
            get {
                return ResourceManager.GetString("ProjectLocationUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the location of the project..
        /// </summary>
        public static string ProjectPickerText {
            get {
                return ResourceManager.GetString("ProjectPickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Compile.
        /// </summary>
        public static string QuickCompileUiText {
            get {
                return ResourceManager.GetString("QuickCompileUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Javascript files after compiling..
        /// </summary>
        public static string RemoveJSFilesUiText {
            get {
                return ResourceManager.GetString("RemoveJSFilesUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveUiText {
            get {
                return ResourceManager.GetString("RemoveUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.js SDK Location.
        /// </summary>
        public static string SdkLocationUiText {
            get {
                return ResourceManager.GetString("SdkLocationUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the location of the SDK folder..
        /// </summary>
        public static string SDKPickerText {
            get {
                return ResourceManager.GetString("SDKPickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsUiText {
            get {
                return ResourceManager.GetString("SettingsUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string SetupUiText {
            get {
                return ResourceManager.GetString("SetupUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string TestUiText {
            get {
                return ResourceManager.GetString("TestUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version D1.03.
        /// </summary>
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting here....
        /// </summary>
        public static string WaitingUiText {
            get {
                return ResourceManager.GetString("WaitingUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting here as well....
        /// </summary>
        public static string WaitingUiText2 {
            get {
                return ResourceManager.GetString("WaitingUiText2", resourceCulture);
            }
        }
    }
}
