//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nwjsCookToolUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nwjsCookToolUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        public static string AbortedText {
            get {
                return ResourceManager.GetString("AbortedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutUiText {
            get {
                return ResourceManager.GetString("AboutUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddUiText {
            get {
                return ResourceManager.GetString("AddUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An argument exception occurred. Possibly a bug in the code.
        ///Check the output in the About tab for more info..
        /// </summary>
        public static string ArgumentExceptionErrorText {
            get {
                return ResourceManager.GetString("ArgumentExceptionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Compile.
        /// </summary>
        public static string BatchCompileUiText {
            get {
                return ResourceManager.GetString("BatchCompileUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing binary files (if present)....
        /// </summary>
        public static string BinRemovalProgressText {
            get {
                return ResourceManager.GetString("BinRemovalProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing binary files from .
        /// </summary>
        public static string BinRemovalStatusText {
            get {
                return ResourceManager.GetString("BinRemovalStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing binary files from the project (if there are)....
        /// </summary>
        public static string BinRemovalText {
            get {
                return ResourceManager.GetString("BinRemovalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string BrowseUiText {
            get {
                return ResourceManager.GetString("BrowseUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelTaskButtonText {
            get {
                return ResourceManager.GetString("CancelTaskButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromium Flags.
        /// </summary>
        public static string ChromiumFlagsUiText {
            get {
                return ResourceManager.GetString("ChromiumFlagsUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation complete!.
        /// </summary>
        public static string CompilationCompleteText {
            get {
                return ResourceManager.GetString("CompilationCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  was compiled..
        /// </summary>
        public static string CompiledOutputText {
            get {
                return ResourceManager.GetString("CompiledOutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling scripts in the js folder....
        /// </summary>
        public static string CompileJsFolderProgressText {
            get {
                return ResourceManager.GetString("CompileJsFolderProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nwjs Compiler is missing..
        /// </summary>
        public static string CompilerMissingText {
            get {
                return ResourceManager.GetString("CompilerMissingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler Status.
        /// </summary>
        public static string CompilerStatusUiText {
            get {
                return ResourceManager.GetString("CompilerStatusUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling .
        /// </summary>
        public static string CompileText {
            get {
                return ResourceManager.GetString("CompileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling scripts in the .
        /// </summary>
        public static string CompileText1 {
            get {
                return ResourceManager.GetString("CompileText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile.
        /// </summary>
        public static string CompileUiText {
            get {
                return ResourceManager.GetString("CompileUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling .
        /// </summary>
        public static string CompilingText {
            get {
                return ResourceManager.GetString("CompilingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression Mode.
        /// </summary>
        public static string CompressionModeUiText {
            get {
                return ResourceManager.GetString("CompressionModeUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying game files to a temporary location....
        /// </summary>
        public static string CopyToTempLocationStatusText {
            get {
                return ResourceManager.GetString("CopyToTempLocationStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by AceOfAces. Licensed under the MIT License..
        /// </summary>
        public static string DevInfoUiText {
            get {
                return ResourceManager.GetString("DevInfoUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A folder was not found. Did it got moved when the work was in progress?
        ///Check the Output in the About tab for more info..
        /// </summary>
        public static string DirectoryNotFoundErrorText {
            get {
                return ResourceManager.GetString("DirectoryNotFoundErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string DoneText {
            get {
                return ResourceManager.GetString("DoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Package Metadata.
        /// </summary>
        public static string EditPackageMetadataButtonText {
            get {
                return ResourceManager.GetString("EditPackageMetadataButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable NodeJS?.
        /// </summary>
        public static string EnableNodeJSCheckBoxText {
            get {
                return ResourceManager.GetString("EnableNodeJSCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ack! An error occured! See the output in the About tab..
        /// </summary>
        public static string ErrorOccuredText {
            get {
                return ResourceManager.GetString("ErrorOccuredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essentials.
        /// </summary>
        public static string EssentialsGroupString {
            get {
                return ResourceManager.GetString("EssentialsGroupString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed!.
        /// </summary>
        public static string FailedText {
            get {
                return ResourceManager.GetString("FailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastest.
        /// </summary>
        public static string FastestListItemText {
            get {
                return ResourceManager.GetString("FastestListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the folder. Please check that you have permission to read and write on the folder..
        /// </summary>
        public static string FileAccessError {
            get {
                return ResourceManager.GetString("FileAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files to a temporary area....
        /// </summary>
        public static string FileCopyText {
            get {
                return ResourceManager.GetString("FileCopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension for compiled files:.
        /// </summary>
        public static string FileExtensionUiText {
            get {
                return ResourceManager.GetString("FileExtensionUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You picked a file that is outside of the project&apos;s file. Please pick a file within the project..
        /// </summary>
        public static string FileOutsideOfProjectError {
            get {
                return ResourceManager.GetString("FileOutsideOfProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File Stream went kaput..
        /// </summary>
        public static string FileStreamErrorText {
            get {
                return ResourceManager.GetString("FileStreamErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file .
        /// </summary>
        public static string FileText {
            get {
                return ResourceManager.GetString("FileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file isn&apos;t available at the moment..
        /// </summary>
        public static string FileUnavailableText {
            get {
                return ResourceManager.GetString("FileUnavailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file was not found. Did a file got moved when the work was in progress?
        ///Check the Output in the About tab for more info..
        /// </summary>
        public static string FineNotFoundErrorText {
            get {
                return ResourceManager.GetString("FineNotFoundErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  folder....
        /// </summary>
        public static string FolderText {
            get {
                return ResourceManager.GetString("FolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ID.
        /// </summary>
        public static string GameIDUiString {
            get {
                return ResourceManager.GetString("GameIDUiString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Info.
        /// </summary>
        public static string GameInfoTabText {
            get {
                return ResourceManager.GetString("GameInfoTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Name.
        /// </summary>
        public static string GameNameUiText {
            get {
                return ResourceManager.GetString("GameNameUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Package Metadata Editor.
        /// </summary>
        public static string GamePackageMetadataEditorTitleText {
            get {
                return ResourceManager.GetString("GamePackageMetadataEditorTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string GameVersionUiString {
            get {
                return ResourceManager.GetString("GameVersionUiString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string HeightUiText {
            get {
                return ResourceManager.GetString("HeightUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML file location.
        /// </summary>
        public static string HTMLFileLocationUiString {
            get {
                return ResourceManager.GetString("HTMLFileLocationUiString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML File|*.html.
        /// </summary>
        public static string HTMLFileText {
            get {
                return ResourceManager.GetString("HTMLFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Location.
        /// </summary>
        public static string IconLocationUiText {
            get {
                return ResourceManager.GetString("IconLocationUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Full Screen.
        /// </summary>
        public static string InFullScreenListItemText {
            get {
                return ResourceManager.GetString("InFullScreenListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Kiosk Mode.
        /// </summary>
        public static string InKioskModeListItemText {
            get {
                return ResourceManager.GetString("InKioskModeListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Invalid operation occurred. See the output for more info..
        /// </summary>
        public static string InvalidOperationErrorText {
            get {
                return ResourceManager.GetString("InvalidOperationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IO Exception occurred. Is an app using the package.json file?.
        /// </summary>
        public static string IOErrorText {
            get {
                return ResourceManager.GetString("IOErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown Input/Output exception occurred.
        ///Check the output in the About tab for more info..
        /// </summary>
        public static string IOExceptionErrorText {
            get {
                return ResourceManager.GetString("IOExceptionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript Flags.
        /// </summary>
        public static string JavaScriptFlagsUiText {
            get {
                return ResourceManager.GetString("JavaScriptFlagsUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Height.
        /// </summary>
        public static string MinimumHeightUiText {
            get {
                return ResourceManager.GetString("MinimumHeightUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Width.
        /// </summary>
        public static string MinimumWidthUiText {
            get {
                return ResourceManager.GetString("MinimumWidthUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nwjs executable is missing..
        /// </summary>
        public static string MissingNwjsExecutableError {
            get {
                return ResourceManager.GetString("MissingNwjsExecutableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Cursor.
        /// </summary>
        public static string MouseCursorListItemText {
            get {
                return ResourceManager.GetString("MouseCursorListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No compression.
        /// </summary>
        public static string NoCompressionListItemText {
            get {
                return ResourceManager.GetString("NoCompressionListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add the folders you want the JavaScript files to be compiled..
        /// </summary>
        public static string NoJSFilesPresent {
            get {
                return ResourceManager.GetString("NoJSFilesPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NoneListItemText {
            get {
                return ResourceManager.GetString("NoneListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t operate on an non-existent folder..
        /// </summary>
        public static string NonExistantFolderText {
            get {
                return ResourceManager.GetString("NonExistantFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.js features.
        /// </summary>
        public static string NWJsFeaturesGroupText {
            get {
                return ResourceManager.GetString("NWJsFeaturesGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimal.
        /// </summary>
        public static string OptimalListItemText {
            get {
                return ResourceManager.GetString("OptimalListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string OutputUiText {
            get {
                return ResourceManager.GetString("OutputUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating package...
        ///.
        /// </summary>
        public static string PackageCreationText {
            get {
                return ResourceManager.GetString("PackageCreationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package the game into package.nw.
        /// </summary>
        public static string PackageProgramUiText {
            get {
                return ResourceManager.GetString("PackageProgramUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging....
        /// </summary>
        public static string PackaginStatusText {
            get {
                return ResourceManager.GetString("PackaginStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path is too long. Please consider shortening the path for the affected folder (see the output for the affected side)..
        /// </summary>
        public static string PathTooLongErrorText {
            get {
                return ResourceManager.GetString("PathTooLongErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG File|*.png.
        /// </summary>
        public static string PNGFileText {
            get {
                return ResourceManager.GetString("PNGFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Information.
        /// </summary>
        public static string ProgramInfoUiText {
            get {
                return ResourceManager.GetString("ProgramInfoUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPG Maker MV Cook Tool.
        /// </summary>
        public static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///---Project Compilation ends here---
        ///
        ///.
        /// </summary>
        public static string ProjectCompilationEndPointText {
            get {
                return ResourceManager.GetString("ProjectCompilationEndPointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///---Project Compilation starts here---.
        /// </summary>
        public static string ProjectCompilationStartPointText {
            get {
                return ResourceManager.GetString("ProjectCompilationStartPointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Folders.
        /// </summary>
        public static string ProjectFoldersUiText {
            get {
                return ResourceManager.GetString("ProjectFoldersUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project location isn&apos;t valid..
        /// </summary>
        public static string ProjectLocationNotValidText {
            get {
                return ResourceManager.GetString("ProjectLocationNotValidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Location.
        /// </summary>
        public static string ProjectLocationUiText {
            get {
                return ResourceManager.GetString("ProjectLocationUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the project is too long. Please shorten the path..
        /// </summary>
        public static string ProjectPathTooLongErrorText {
            get {
                return ResourceManager.GetString("ProjectPathTooLongErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the location of the project..
        /// </summary>
        public static string ProjectPickerText {
            get {
                return ResourceManager.GetString("ProjectPickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Compile.
        /// </summary>
        public static string QuickCompileUiText {
            get {
                return ResourceManager.GetString("QuickCompileUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Javascript files after compiling..
        /// </summary>
        public static string RemoveJSFilesUiText {
            get {
                return ResourceManager.GetString("RemoveJSFilesUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove source files after packaging..
        /// </summary>
        public static string RemoveSourceFilesUIText {
            get {
                return ResourceManager.GetString("RemoveSourceFilesUIText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveUiText {
            get {
                return ResourceManager.GetString("RemoveUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement Code.
        /// </summary>
        public static string ReplacementCodeUiText {
            get {
                return ResourceManager.GetString("ReplacementCodeUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizable Window?.
        /// </summary>
        public static string ResizableWindowUiText {
            get {
                return ResourceManager.GetString("ResizableWindowUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string ResolutionUiText {
            get {
                return ResourceManager.GetString("ResolutionUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression Safe Mode.
        /// </summary>
        public static string SafeModeUiText {
            get {
                return ResourceManager.GetString("SafeModeUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package metadata file was saved successfully..
        /// </summary>
        public static string SaveCompleteText {
            get {
                return ResourceManager.GetString("SaveCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Center.
        /// </summary>
        public static string ScreenCenterListItemText {
            get {
                return ResourceManager.GetString("ScreenCenterListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.js SDK Location.
        /// </summary>
        public static string SdkLocationUiText {
            get {
                return ResourceManager.GetString("SdkLocationUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the location of the SDK folder..
        /// </summary>
        public static string SDKPickerText {
            get {
                return ResourceManager.GetString("SDKPickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsUiText {
            get {
                return ResourceManager.GetString("SettingsUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string SetupUiText {
            get {
                return ResourceManager.GetString("SetupUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---Start Task---
        ///.
        /// </summary>
        public static string StartTaskPointText {
            get {
                return ResourceManager.GetString("StartTaskPointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        public static string StartUiText {
            get {
                return ResourceManager.GetString("StartUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task was cancelled..
        /// </summary>
        public static string TaskCancelledMessage {
            get {
                return ResourceManager.GetString("TaskCancelledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task was cancelled by the user..
        /// </summary>
        public static string TaskCancelledOutputText {
            get {
                return ResourceManager.GetString("TaskCancelledOutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---Ended Task---
        ///.
        /// </summary>
        public static string TaskEndPointText {
            get {
                return ResourceManager.GetString("TaskEndPointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string TestUiText {
            get {
                return ResourceManager.GetString("TestUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program can&apos;t access a file.
        ///Check the output in the About tab for more info..
        /// </summary>
        public static string UnauthorizedAccessErrorText {
            get {
                return ResourceManager.GetString("UnauthorizedAccessErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version R2.01 Update 1.
        /// </summary>
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting here....
        /// </summary>
        public static string WaitingUiText {
            get {
                return ResourceManager.GetString("WaitingUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting here as well....
        /// </summary>
        public static string WaitingUiText2 {
            get {
                return ResourceManager.GetString("WaitingUiText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string WidthUiText {
            get {
                return ResourceManager.GetString("WidthUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Win32 API error occurred. See the output for more info..
        /// </summary>
        public static string Win32ApiErrorText {
            get {
                return ResourceManager.GetString("Win32ApiErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed.
        /// </summary>
        public static string WindowedListItemText {
            get {
                return ResourceManager.GetString("WindowedListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string WindowGroupText {
            get {
                return ResourceManager.GetString("WindowGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Position.
        /// </summary>
        public static string WindowPositionUiText {
            get {
                return ResourceManager.GetString("WindowPositionUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Settings.
        /// </summary>
        public static string WindowSettingsUiText {
            get {
                return ResourceManager.GetString("WindowSettingsUiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Size.
        /// </summary>
        public static string WindowSizeGroupText {
            get {
                return ResourceManager.GetString("WindowSizeGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Title.
        /// </summary>
        public static string WindowTitleUiText {
            get {
                return ResourceManager.GetString("WindowTitleUiText", resourceCulture);
            }
        }
    }
}
