//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMMVCookTool.CLI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RMMVCookTool.CLI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing binary files (if present)....
        /// </summary>
        internal static string BinaryRemovalText {
            get {
                return ResourceManager.GetString("BinaryRemovalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t compress and test the project at the moment..
        /// </summary>
        internal static string CannotCompressAndTestErrorText {
            get {
                return ResourceManager.GetString("CannotCompressAndTestErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [orange1]Command line arguments[/].
        /// </summary>
        internal static string CommandLineArgsTitle {
            get {
                return ResourceManager.GetString("CommandLineArgsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string CommonWordNo {
            get {
                return ResourceManager.GetString("CommonWordNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string CommonWordYes {
            get {
                return ResourceManager.GetString("CommonWordYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job is aborted due to an issue with the nwjs compiler. Please check the file and try again.
        ///.
        /// </summary>
        internal static string CompilerErrorText {
            get {
                return ResourceManager.GetString("CompilerErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compiler isn&apos;t there. Please pick the folder that has the nwjc file..
        /// </summary>
        internal static string CompilerMissingErrorText {
            get {
                return ResourceManager.GetString("CompilerMissingErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished compiling files..
        /// </summary>
        internal static string CompilerTaskComplete {
            get {
                return ResourceManager.GetString("CompilerTaskComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is compiling .
        /// </summary>
        internal static string CompilingWord {
            get {
                return ResourceManager.GetString("CompilingWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling .
        /// </summary>
        internal static string CompilingWord2 {
            get {
                return ResourceManager.GetString("CompilingWord2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress and remove source files.
        /// </summary>
        internal static string CompressAndRemoveEntry {
            get {
                return ResourceManager.GetString("CompressAndRemoveEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression.
        /// </summary>
        internal static string CompressionEntry {
            get {
                return ResourceManager.GetString("CompressionEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression Level.
        /// </summary>
        internal static string CompressionLevelEntry {
            get {
                return ResourceManager.GetString("CompressionLevelEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression is not allowed if the &quot;--PackageApp&quot; command line argument is specified. Skipping this step..
        /// </summary>
        internal static string CompressionNotPermittedText {
            get {
                return ResourceManager.GetString("CompressionNotPermittedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Would you like to compress the game&apos;s files to an archive?
        ///1.Yes (delete the files as well).
        ///2.Yes (but leave the files intact).
        ///3. No.
        ///(Default is 3).
        /// </summary>
        internal static string CompressionQuestion {
            get {
                return ResourceManager.GetString("CompressionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe mode for compression is now active..
        /// </summary>
        internal static string CompressionSafeModeConfirmationText {
            get {
                return ResourceManager.GetString("CompressionSafeModeConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress only.
        /// </summary>
        internal static string CompressOnlyEntry {
            get {
                return ResourceManager.GetString("CompressOnlyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying the game files to a temporary location....
        /// </summary>
        internal static string CopyingToTempLocationText {
            get {
                return ResourceManager.GetString("CopyingToTempLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [darkcyan]Compiling JS files[/].
        /// </summary>
        internal static string DarkcyanCompilingJSFilesText {
            get {
                return ResourceManager.GetString("DarkcyanCompilingJSFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}].
        /// </summary>
        internal static string DateTimeFormatText {
            get {
                return ResourceManager.GetString("DateTimeFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastest.
        /// </summary>
        internal static string FastestCompression {
            get {
                return ResourceManager.GetString("FastestCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fastest compression will be used for the archive..
        /// </summary>
        internal static string FastestCompressionConfirmationText {
            get {
                return ResourceManager.GetString("FastestCompressionConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing files....
        /// </summary>
        internal static string FileCompressionText {
            get {
                return ResourceManager.GetString("FileCompressionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Extension.
        /// </summary>
        internal static string FileExtensionEntry {
            get {
                return ResourceManager.GetString("FileExtensionEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///What Extension will your game use (leave empty for .bin)? .
        /// </summary>
        internal static string FileExtensionQuestion {
            get {
                return ResourceManager.GetString("FileExtensionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file extension is set to .
        /// </summary>
        internal static string FileExtensionSetText {
            get {
                return ResourceManager.GetString("FileExtensionSetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  finished compiling .
        /// </summary>
        internal static string FinishedCompilingText {
            get {
                return ResourceManager.GetString("FinishedCompilingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished compiling .
        /// </summary>
        internal static string FinishedCompilingText2 {
            get {
                return ResourceManager.GetString("FinishedCompilingText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JavaScript files will be deleted after compilation..
        /// </summary>
        internal static string JavascriptDeletionConfirmationTet {
            get {
                return ResourceManager.GetString("JavascriptDeletionConfirmationTet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package.json file doesn&apos;t exist..
        /// </summary>
        internal static string JsonFileMissingErrorText {
            get {
                return ResourceManager.GetString("JsonFileMissingErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reference was found on the package.json (or the folder mentioned isn&apos;t there). Please check that the json file contains the &quot;main&quot; variable and the folder exists..
        /// </summary>
        internal static string JsonReferenceError {
            get {
                return ResourceManager.GetString("JsonReferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No compression.
        /// </summary>
        internal static string NoCompression {
            get {
                return ResourceManager.GetString("NoCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No compression will be used for the archive..
        /// </summary>
        internal static string NoCompressionConfirmationText {
            get {
                return ResourceManager.GetString("NoCompressionConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///NW.js will now start. Give it a few seconds to start..
        /// </summary>
        internal static string NwjsStartingTestNotificationText {
            get {
                return ResourceManager.GetString("NwjsStartingTestNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.js will start after compiling..
        /// </summary>
        internal static string nwjsTestStartingText {
            get {
                return ResourceManager.GetString("nwjsTestStartingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimal.
        /// </summary>
        internal static string OptimalCompression {
            get {
                return ResourceManager.GetString("OptimalCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The optimal compression will be used for the archive (this is the default)..
        /// </summary>
        internal static string OptimalCompressionCOnfirmationText {
            get {
                return ResourceManager.GetString("OptimalCompressionCOnfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging the game files....
        /// </summary>
        internal static string PackagingGameText {
            get {
                return ResourceManager.GetString("PackagingGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler is now running in parallel mode..
        /// </summary>
        internal static string ParallelModeActiveText {
            get {
                return ResourceManager.GetString("ParallelModeActiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Developed by AceOfAces..
        /// </summary>
        internal static string ProgramAuthorText {
            get {
                return ResourceManager.GetString("ProgramAuthorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Licensed under the MIT license..
        /// </summary>
        internal static string ProgramLicenseText {
            get {
                return ResourceManager.GetString("ProgramLicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = RPG Maker MV Cook Tool (.NET Core CLI Version).
        /// </summary>
        internal static string ProgramNameText {
            get {
                return ResourceManager.GetString("ProgramNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Version R2.03 ({0}).
        /// </summary>
        internal static string ProgramVersionString {
            get {
                return ResourceManager.GetString("ProgramVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Project&apos;s files will be compressed.
        /// </summary>
        internal static string ProjectFilesCompressionConfirmText {
            get {
                return ResourceManager.GetString("ProjectFilesCompressionConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project&apos;s files will be compressed (the files will be deleted after compressing)..
        /// </summary>
        internal static string ProjectFilesRemovalAfterCompressionText {
            get {
                return ResourceManager.GetString("ProjectFilesRemovalAfterCompressionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no js folder.
        ///.
        /// </summary>
        internal static string ProjectJsFolderMissing {
            get {
                return ResourceManager.GetString("ProjectJsFolderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Location OK..
        /// </summary>
        internal static string ProjectLocationConfirmationText {
            get {
                return ResourceManager.GetString("ProjectLocationConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Location.
        /// </summary>
        internal static string ProjectLocationEntry {
            get {
                return ResourceManager.GetString("ProjectLocationEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of the project doesn&apos;t exist..
        /// </summary>
        internal static string ProjectLocationInexistantText {
            get {
                return ResourceManager.GetString("ProjectLocationInexistantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the location of the folder.
        ///.
        /// </summary>
        internal static string ProjectLocationIsNullText {
            get {
                return ResourceManager.GetString("ProjectLocationIsNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Where&apos;s the project you want to compile? .
        /// </summary>
        internal static string ProjectLocationQuestion {
            get {
                return ResourceManager.GetString("ProjectLocationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Project location is not set. Please set it with the --ProjectLocation &quot;&lt;project location&gt;&quot;..
        /// </summary>
        internal static string ProjectNotSetErrorText {
            get {
                return ResourceManager.GetString("ProjectNotSetErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder you&apos;ve selected isn&apos;t present.
        ///.
        /// </summary>
        internal static string ProjetDirectoryMissingErrorText {
            get {
                return ResourceManager.GetString("ProjetDirectoryMissingErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Enter/Return to exit..
        /// </summary>
        internal static string PushEnterToExitText {
            get {
                return ResourceManager.GetString("PushEnterToExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove source JS files.
        /// </summary>
        internal static string RemoveSourceFilesEntry {
            get {
                return ResourceManager.GetString("RemoveSourceFilesEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory isn&apos;t there. Please select an existing folder.
        ///.
        /// </summary>
        internal static string SDKDirectoryMissing {
            get {
                return ResourceManager.GetString("SDKDirectoryMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK Location OK..
        /// </summary>
        internal static string SDKLocationConfirmationText {
            get {
                return ResourceManager.GetString("SDKLocationConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK Location.
        /// </summary>
        internal static string SDKLocationEntry {
            get {
                return ResourceManager.GetString("SDKLocationEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of the SDK doesn&apos;t exist..
        /// </summary>
        internal static string SDKLocationInexistantText {
            get {
                return ResourceManager.GetString("SDKLocationInexistantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert the path for the SDK.
        ///.
        /// </summary>
        internal static string SDKLocationIsNullText {
            get {
                return ResourceManager.GetString("SDKLocationIsNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SDK location is not set. Please set it with the --SDKLocation &quot;&lt;project location&gt;&quot;..
        /// </summary>
        internal static string SDKLocationNotSetErrorText {
            get {
                return ResourceManager.GetString("SDKLocationNotSetErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where&apos;s the SDK location? .
        /// </summary>
        internal static string SDKLocationQuestion {
            get {
                return ResourceManager.GetString("SDKLocationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string SettingTitle {
            get {
                return ResourceManager.GetString("SettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [orange1]Setup[/].
        /// </summary>
        internal static string SetupTitle {
            get {
                return ResourceManager.GetString("SetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting source files....
        /// </summary>
        internal static string SourceFileDeletionText {
            get {
                return ResourceManager.GetString("SourceFileDeletionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ================================================.
        /// </summary>
        internal static string SpilterText {
            get {
                return ResourceManager.GetString("SpilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The task was completed..
        /// </summary>
        internal static string TaskCompleteText {
            get {
                return ResourceManager.GetString("TaskCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test after compiling.
        /// </summary>
        internal static string TestAfterCompilingEntry {
            get {
                return ResourceManager.GetString("TestAfterCompilingEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Would you like to test the project after compiling? (Y/N, Default is N)
        ///.
        /// </summary>
        internal static string TestProjectQuestion {
            get {
                return ResourceManager.GetString("TestProjectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ]Thread #.
        /// </summary>
        internal static string ThreadWord {
            get {
                return ResourceManager.GetString("ThreadWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ValueTitle {
            get {
                return ResourceManager.GetString("ValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Do you want to:
        ///1. Test that the binary files are loaded properly?
        ///2. Prepare for publishing?
        ///(Default is 1) .
        /// </summary>
        internal static string WorkloadQuestion {
            get {
                return ResourceManager.GetString("WorkloadQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [orange1]Work[/].
        /// </summary>
        internal static string WorkTitle {
            get {
                return ResourceManager.GetString("WorkTitle", resourceCulture);
            }
        }
    }
}
